### ISSUE TITLE
rust 1.74 build error

### ISSUE THREAD

**Issue by ImKK666** [memflow/memflow#103]
The compilable version of RUST is less than 1.70. Testing with 1.69 and below works, but not with 1.70 and above.

file:
https://github.com/memflow/memflow/blob/ec4d19b5600597d0f9e463c3ad085af288f77f5c/memflow/src/plugins/mod.rs#L37C1-L37C37

pub use logger::*; // TODO: restrict

```
kk@kk-ubuntu:~/code/rust/memflow$ cargo build --release
   Compiling memchr v2.5.0
   Compiling cast v0.2.7
   Compiling num-traits v0.2.15
   Compiling unicode-width v0.1.10
   Compiling itertools v0.9.0
   Compiling regex-syntax v0.6.29
   Compiling same-file v1.0.6
   Compiling tinytemplate v1.2.1
   Compiling oorandom v11.1.3
   Compiling memflow v0.2.0-beta10 (/home/kk/code/rust/memflow/memflow)
   Compiling textwrap v0.11.0
   Compiling walkdir v2.3.3
   Compiling clap v2.34.0
   Compiling csv-core v0.1.10
   Compiling csv v1.2.1
   Compiling criterion-plot v0.4.2 (https://github.com/h33p/criterion.rs.git?branch=tput#e6a0f215)
   Compiling regex v1.7.2
warning: ambiguous glob re-exports
  --> memflow/src/plugins/mod.rs:37:9
   |
37 | pub use logger::*; // TODO: restrict
   |         ^^^^^^^^^ the name `Metadata` in the type namespace is first re-exported here
...
44 | use log::*;
   |     ------ but the name `Metadata` in the type namespace is also re-exported here
   |
   = note: `#[warn(ambiguous_glob_reexports)]` on by default

warning: ambiguous glob re-exports
  --> memflow/src/plugins/mod.rs:37:9
   |
37 | pub use logger::*; // TODO: restrict
   |         ^^^^^^^^^ the name `Record` in the type namespace is first re-exported here
...
44 | use log::*;
   |     ------ but the name `Record` in the type namespace is also re-exported here

warning: ambiguous glob re-exports
   --> memflow/src/lib.rs:286:17
    |
286 |         pub use crate::os::*;
    |                 ^^^^^^^^^^^^ the name `util` in the type namespace is first re-exported here
...
291 |         pub use crate::types::*;
    |                 --------------- but the name `util` in the type namespace is also re-exported here

   Compiling plotters v0.2.15
   Compiling criterion v0.3.2 (https://github.com/h33p/criterion.rs.git?branch=tput#e6a0f215)
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: NormalizationFailure(std::option::Option<&<T as plugins::Loadable>::ArgsType>, Type(std::option::Option<&<T as plugins::Loadable>::ArgsType>))', compiler/rustc_lint/src/types.rs:916:88
stack backtrace:
   0:     0x7fd8a83f4b61 - std::backtrace_rs::backtrace::libunwind::trace::he648b5c8dd376705
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fd8a83f4b61 - std::backtrace_rs::backtrace::trace_unsynchronized::h5da3e203eef39e9f
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fd8a83f4b61 - std::sys_common::backtrace::_print_fmt::h8d28d3f20588ae4c
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7fd8a83f4b61 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a5b0c9c6b058c0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7fd8a845b77f - core::fmt::rt::Argument::fmt::h0afc04119f252b53
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
   5:     0x7fd8a845b77f - core::fmt::write::h50b1b3e73851a6fe
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
   6:     0x7fd8a83e74a7 - std::io::Write::write_fmt::h184eaf275e4484f0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
   7:     0x7fd8a83f4975 - std::sys_common::backtrace::_print::hf58c3a5a25090e71
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7fd8a83f4975 - std::sys_common::backtrace::print::hb9cf0a7c7f077819
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fd8a83f7753 - std::panicking::default_hook::{{closure}}::h066adb2e3f3e2c07
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
  10:     0x7fd8a83f74e4 - std::panicking::default_hook::h277fa2776900ff14
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:288:9
  11:     0x7fd8a726756b - <rustc_driver_impl[10725d833993dc31]::install_ice_hook::{closure#0} as core[f12ae36cc2e1ecf0]::ops::function::FnOnce<(&core[f12ae36cc2e1ecf0]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  12:     0x7fd8a83f7f7e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h09cad52ea08435f2
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:2007:9
  13:     0x7fd8a83f7f7e - std::panicking::rust_panic_with_hook::hceaf38da6d9db792
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:709:13
  14:     0x7fd8a83f7d07 - std::panicking::begin_panic_handler::{{closure}}::h2bce3ed2516af7df
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
  15:     0x7fd8a83f4fc6 - std::sys_common::backtrace::__rust_end_short_backtrace::h090f3faf8f98a395
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
  16:     0x7fd8a83f7a52 - rust_begin_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
  17:     0x7fd8a84579f3 - core::panicking::panic_fmt::h4ec8274704d163a3
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
  18:     0x7fd8a8458013 - core::result::unwrap_failed::h170bc2721a6c6ff2
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
  19:     0x7fd8a63b4558 - rustc_lint[9d740a8528938e29]::types::repr_nullable_ptr
  20:     0x7fd8a63b3259 - <rustc_lint[9d740a8528938e29]::types::ImproperCTypesVisitor>::check_type_for_ffi
  21:     0x7fd8a63b340b - <rustc_lint[9d740a8528938e29]::types::ImproperCTypesVisitor>::check_type_for_ffi
  22:     0x7fd8a62e5a4a - <rustc_lint[9d740a8528938e29]::types::ImproperCTypesVisitor>::check_type_for_ffi_and_report_errors
  23:     0x7fd8a547b910 - <rustc_lint[9d740a8528938e29]::types::ImproperCTypesDefinitions>::check_ty_maybe_containing_foreign_fnptr
  24:     0x7fd8a533d821 - <rustc_lint[9d740a8528938e29]::BuiltinCombinedModuleLateLintPass as rustc_lint[9d740a8528938e29]::passes::LateLintPass>::check_item
  25:     0x7fd8a5339336 - rustc_hir[c7c79bd3af2232c6]::intravisit::walk_mod::<rustc_lint[9d740a8528938e29]::late::LateContextAndPass<rustc_lint[9d740a8528938e29]::BuiltinCombinedModuleLateLintPass>>
  26:     0x7fd8a5338c46 - rustc_lint[9d740a8528938e29]::late::late_lint_mod::<rustc_lint[9d740a8528938e29]::BuiltinCombinedModuleLateLintPass>
  27:     0x7fd8a53389fc - rustc_lint[9d740a8528938e29]::lint_mod
  28:     0x7fd8a5e6c37c - rustc_query_impl[7f6201a046a7a363]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7f6201a046a7a363]::query_impl::lint_mod::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4cadb439cfabc8cf]::query::erase::Erased<[u8; 0usize]>>
  29:     0x7fd8a5e6c35e - <rustc_query_impl[7f6201a046a7a363]::query_impl::lint_mod::dynamic_query::{closure#2} as core[f12ae36cc2e1ecf0]::ops::function::FnOnce<(rustc_middle[4cadb439cfabc8cf]::ty::context::TyCtxt, rustc_span[14af2d27fb997609]::def_id::LocalDefId)>>::call_once
  30:     0x7fd8a593344f - rustc_query_system[5a9d202ec1d2890c]::query::plumbing::try_execute_query::<rustc_query_impl[7f6201a046a7a363]::DynamicConfig<rustc_query_system[5a9d202ec1d2890c]::query::caches::VecCache<rustc_span[14af2d27fb997609]::def_id::LocalDefId, rustc_middle[4cadb439cfabc8cf]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[7f6201a046a7a363]::plumbing::QueryCtxt, false>
  31:     0x7fd8a6bae604 - rustc_query_impl[7f6201a046a7a363]::query_impl::lint_mod::get_query_non_incr::__rust_end_short_backtrace
  32:     0x7fd8a662f967 - rustc_data_structures[cf1e21f3f9509cab]::sync::par_for_each_in::<&[rustc_hir[c7c79bd3af2232c6]::hir_id::OwnerId], <rustc_middle[4cadb439cfabc8cf]::hir::map::Map>::par_for_each_module<rustc_lint[9d740a8528938e29]::late::check_crate<rustc_lint[9d740a8528938e29]::BuiltinCombinedLateLintPass, rustc_interface[7e6a9899d53a1fe5]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}::{closure#0}>::{closure#0}>
  33:     0x7fd8a662f6b5 - <rustc_session[c98e5f13e8087e38]::session::Session>::time::<(), rustc_lint[9d740a8528938e29]::late::check_crate<rustc_lint[9d740a8528938e29]::BuiltinCombinedLateLintPass, rustc_interface[7e6a9899d53a1fe5]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}::{closure#0}>::{closure#1}::{closure#0}>
  34:     0x7fd8a662f2ee - <rustc_session[c98e5f13e8087e38]::session::Session>::time::<(), rustc_interface[7e6a9899d53a1fe5]::passes::analysis::{closure#5}::{closure#1}::{closure#2}::{closure#0}>
  35:     0x7fd8a662ee0f - <core[f12ae36cc2e1ecf0]::panic::unwind_safe::AssertUnwindSafe<rustc_interface[7e6a9899d53a1fe5]::passes::analysis::{closure#5}::{closure#1}> as core[f12ae36cc2e1ecf0]::ops::function::FnOnce<()>>::call_once
  36:     0x7fd8a662e800 - <rustc_session[c98e5f13e8087e38]::session::Session>::time::<(), rustc_interface[7e6a9899d53a1fe5]::passes::analysis::{closure#5}>
  37:     0x7fd8a662d2d7 - rustc_interface[7e6a9899d53a1fe5]::passes::analysis
  38:     0x7fd8a667dcfa - rustc_query_impl[7f6201a046a7a363]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[7f6201a046a7a363]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[4cadb439cfabc8cf]::query::erase::Erased<[u8; 1usize]>>
  39:     0x7fd8a667dce9 - <rustc_query_impl[7f6201a046a7a363]::query_impl::analysis::dynamic_query::{closure#2} as core[f12ae36cc2e1ecf0]::ops::function::FnOnce<(rustc_middle[4cadb439cfabc8cf]::ty::context::TyCtxt, ())>>::call_once
  40:     0x7fd8a68b1318 - rustc_query_system[5a9d202ec1d2890c]::query::plumbing::try_execute_query::<rustc_query_impl[7f6201a046a7a363]::DynamicConfig<rustc_query_system[5a9d202ec1d2890c]::query::caches::SingleCache<rustc_middle[4cadb439cfabc8cf]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[7f6201a046a7a363]::plumbing::QueryCtxt, false>
  41:     0x7fd8a68b10e9 - rustc_query_impl[7f6201a046a7a363]::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
  42:     0x7fd8a672ddf2 - <rustc_interface[7e6a9899d53a1fe5]::queries::QueryResult<&rustc_middle[4cadb439cfabc8cf]::ty::context::GlobalCtxt>>::enter::<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}::{closure#2}::{closure#4}>
  43:     0x7fd8a672ca97 - <rustc_interface[7e6a9899d53a1fe5]::interface::Compiler>::enter::<rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}::{closure#2}, core[f12ae36cc2e1ecf0]::result::Result<core[f12ae36cc2e1ecf0]::option::Option<rustc_interface[7e6a9899d53a1fe5]::queries::Linker>, rustc_span[14af2d27fb997609]::ErrorGuaranteed>>
  44:     0x7fd8a6729cc5 - rustc_span[14af2d27fb997609]::set_source_map::<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_interface[7e6a9899d53a1fe5]::interface::run_compiler<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  45:     0x7fd8a6729736 - <scoped_tls[a7f541bbfecfca9d]::ScopedKey<rustc_span[14af2d27fb997609]::SessionGlobals>>::set::<rustc_interface[7e6a9899d53a1fe5]::interface::run_compiler<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}>::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>
  46:     0x7fd8a6728cfc - std[7c7acd4e376d60d3]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[7e6a9899d53a1fe5]::util::run_in_thread_pool_with_globals<rustc_interface[7e6a9899d53a1fe5]::interface::run_compiler<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}>::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>
  47:     0x7fd8a6aa1305 - <<std[7c7acd4e376d60d3]::thread::Builder>::spawn_unchecked_<rustc_interface[7e6a9899d53a1fe5]::util::run_in_thread_pool_with_globals<rustc_interface[7e6a9899d53a1fe5]::interface::run_compiler<core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>, rustc_driver_impl[10725d833993dc31]::run_compiler::{closure#1}>::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[f12ae36cc2e1ecf0]::result::Result<(), rustc_span[14af2d27fb997609]::ErrorGuaranteed>>::{closure#1} as core[f12ae36cc2e1ecf0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  48:     0x7fd8a8402435 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc0b1022758ecac73
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  49:     0x7fd8a8402435 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0c9654ebe7ad657e
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  50:     0x7fd8a8402435 - std::sys::unix::thread::Thread::new::thread_start::h04c8e9c7d83d3bd5
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7fd8a3c94b43 - start_thread
                               at ./nptl/pthread_create.c:442:8
  52:     0x7fd8a3d26a00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  53:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.72.0 (5680fa18f 2023-08-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [lint_mod] linting module `plugins`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: `memflow` (lib) generated 3 warnings
error: could not compile `memflow` (lib); 3 warnings emitted
warning: build failed, waiting for other jobs to finish...

```

**Comment by ko1N** [comment]
Urgh, i briefly looked into it and it seems like a regression in how GATs are resolved in the rust compiler itself.

The culprit is this type alias:
```
pub type CreateFn<T> = extern "C" fn(
    Option<&<T as Loadable>::ArgsType>,
    <T as Loadable>::CInputArg,
    lib: LibArc,
    logger: Option<&'static PluginLogger>,
    &mut MaybeUninit<<T as Loadable>::Instance>,
) -> i32;
```

More specifically the reference in the option for the `ArgsType`

The corresponding rust issue referencing this can be found here: https://github.com/rust-lang/rust/issues/115143

Not sure what we could change to work around this issue as of right now. Id recommend downgrading to 1.69 for now. Sorry!

**Comment by ko1N** [comment]
This is now fixed upstream 👍
